#' @title Filter First Time Point Based on Monotone Trend
#'
#' @description
#' This function applies monotone trend filtering to the first time point in a pSILAC labeling series, based on the specified mode.
#' Depending on whether the values represent `RIA`, `HOL`, or `NLI` data, the function filters rows according to the monotonicity assumption:
#' a decreasing trend for `RIA` and `NLI`, and an increasing trend for `HOL`.
#'
#' @param data A data frame representing values from a single pSILAC labeling series, where each row corresponds to one observation.
#' @param mode Specifies the type of data values:
#'   - `"RIA"`: Assumes a monotone decreasing trend for the first time point.
#'   - `"HOL"`: Assumes a monotone increasing trend for the first time point.
#'   - `"NLI"`: Assumes a monotone decreasing trend for the first time point.
#'   The mode determines the filtering criteria applied.
#' @importFrom dplyr filter select bind_rows
#'
#' @return
#' Returns a filtered data frame with the same columns as the input `data`, where the first time point is adjusted based on the specified monotonic trend criteria.
#'
#' @export
filterMonotoneTp1Only <- function(data, mode = NULL){
  
  if(is.null(mode)){
    stop("Please specify the datatype (ria, hol) to use the correct assumption")
  }
  
  # report the first value from the vector generated by diff function per row
  # in those with non-missing values in tp1, this values corresponds to the difference from the next value
  data$compare_timepoints <- apply(data, 1, function(x){diff(na.omit(x))[1]})
  data$isna_tp1 <- is.na(data[,1])
  
  data_tp1_missing <- data %>%
    filter(isna_tp1 == TRUE)
  
  data_tp1_decide <- data %>%
    filter(isna_tp1 == FALSE)
  
  if(mode == "RIA"){
    
    data_tp1_decide[,1] <- ifelse(data_tp1_decide$compare_timepoints < 0, data_tp1_decide[,1], NA)
    
    data_filtered <- data_tp1_decide %>%
      bind_rows(data_tp1_missing) %>%
      select(-compare_timepoints, -isna_tp1)
    
  } else if(mode == "NLI"){
    
    data_tp1_decide[,1] <- ifelse(data_tp1_decide$compare_timepoints < 0, data_tp1_decide[,1], NA)
    
    data_filtered <- data_tp1_decide %>%
      bind_rows(data_tp1_missing) %>%
      select(-compare_timepoints, -isna_tp1)
    
  } else if(mode == "HOL"){
    
    data_tp1_decide[,1] <- ifelse(data_tp1_decide$compare_timepoints > 0, data_tp1_decide[,1], NA)
    
    data_filtered <- data_tp1_decide %>%
      bind_rows(data_tp1_missing) %>%
      select(-compare_timepoints, -isna_tp1)
    
  }
  
  return(data_filtered)
  
}

